version: '3'

services:
  # Nginx service for reverse proxy with Basic Auth
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-}
    # Script îmbunătățit cu htpasswd (care există în nginx:alpine)
    command: >
      sh -c "
        if [ -n \"$$AUTH_PASSWORD\" ]; then
          echo 'Installing htpasswd and enabling Basic Auth...'
          apk add --no-cache apache2-utils &&
          htpasswd -cb /etc/nginx/.htpasswd \"$$AUTH_USERNAME\" \"$$AUTH_PASSWORD\" &&
          echo 'Basic Auth enabled for user:' $$AUTH_USERNAME &&
          cat /etc/nginx/.htpasswd
        else
          echo 'Basic Auth disabled - no password set'
          rm -f /etc/nginx/.htpasswd
        fi &&
        nginx -g 'daemon off;'
      "

  # Frontend service  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=/api
    restart: unless-stopped

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - uploaded_videos:/app/uploads
      - processed_videos:/app/processed
      - whisper_models:/root/.cache/whisper
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-3000MB}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CORS_ORIGINS=*
      - PYTHONUNBUFFERED=1
      - MALLOC_ARENA_MAX=2
      - BACKEND_API_KEY=${BACKEND_API_KEY:-}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-false}
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  uploaded_videos:
  processed_videos:
  whisper_models: