version: '3'

services:
  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=/api
    restart: unless-stopped

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - uploaded_videos:/app/uploads
      - processed_videos:/app/processed
      - whisper_models:/root/.cache/whisper
    environment:
      - WHISPER_MODEL=small
      - MAX_UPLOAD_SIZE=3000MB
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CORS_ORIGINS=*
    ports:
      - "5000:5000"  # Expunem portul pentru debugging
    restart: unless-stopped

volumes:
  uploaded_videos:
  processed_videos:
  whisper_models: