version: '3'

services:
  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=/api
    restart: unless-stopped

  # Backend service - OPTIMIZAT pentru selector dinamic de modele Whisper
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - uploaded_videos:/app/uploads
      - processed_videos:/app/processed
      - whisper_models:/root/.cache/whisper  # Cache persistent pentru modele
    environment:
      # Model inițial la pornire - utilizatorul poate schimba prin interfață
      - WHISPER_MODEL=small
      # Configurare pentru modele multiple
      - MAX_UPLOAD_SIZE=3000MB
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CORS_ORIGINS=*
      # Setări pentru gestionarea memoriei cu modele multiple
      - PYTHONUNBUFFERED=1
      - MALLOC_ARENA_MAX=2
    ports:
      - "5000:5000"  # Expunem portul pentru debugging
    # Configurare memorie pentru modele mari
    deploy:
      resources:
        limits:
          # Limitare memorie pentru a preveni crash-urile cu modele mari
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
    # Setări pentru debugging și monitorizare
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  uploaded_videos:
  processed_videos:
  # Volume persistent pentru cache-ul modelelor Whisper
  # Evită descărcarea repetată a modelelor la restart
  whisper_models: